[package]
name = "stream-coin"
version = "0.1.0"
authors = ["Navid Sadeghi navidsadeghi0021@gmail.com, navidsadeghi2@outlook.com"]
edition = "2021"
license = "GPL-3"

[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0.217", features = ["derive"] }
