use chrono::{DateTime, Utc};
use tokio::sync::Mutex;

/// Determines how fill prices are calculated when a pending order is matched
/// against a candle close.
#[derive(Debug, Clone)]
pub enum FillModel {
    /// Fill at the exact close price — no slippage.
    LastClose,
    /// Add/subtract a fixed spread expressed in basis points (1 bp = 0.01 %).
    /// Buys are filled slightly above close; sells are filled slightly below.
    Slippage { basis_points: u64 },
}

impl FillModel {
    pub fn apply(&self, close_price: u64, side: &str) -> u64 {
        match self {
            FillModel::LastClose => close_price,
            FillModel::Slippage { basis_points } => {
                // Ceiling integer division to avoid zero slippage on tiny prices.
                let slippage = close_price
                    .saturating_mul(*basis_points)
                    .saturating_add(9_999)
                    / 10_000;
                match side {
                    "buy" => close_price.saturating_add(slippage),
                    "sell" => close_price.saturating_sub(slippage),
                    _ => close_price,
                }
            }
        }
    }
}

/// An order that has been placed but not yet filled.
pub struct PendingOrder {
    pub order_id: String,
    pub side: String,
    pub quantity: u64,
    pub strategy_id: String,
    /// The time at which the order was placed (i.e. the time of the candle that
    /// triggered the signal).  Only candles whose `time` is strictly AFTER this
    /// value may fill the order — this is the time-frontier invariant that
    /// prevents look-ahead bias.
    pub placed_at: DateTime<Utc>,
}

#[derive(Debug, Clone)]
pub struct SimulatedFill {
    pub order_id: String,
    pub side: String,
    pub quantity: u64,
    pub fill_price: u64,
    pub strategy_id: String,
    pub candle_time: DateTime<Utc>,
}

/// In-memory simulated venue used during backtesting.
///
/// Orders are filled at the close price of the first candle whose time is
/// strictly after `PendingOrder::placed_at`.  This prevents look-ahead bias:
/// a signal generated by candle N cannot be filled by candle N itself.
pub struct SimulatedVenue {
    fill_model: FillModel,
    pending: Mutex<Vec<PendingOrder>>,
    fills: Mutex<Vec<SimulatedFill>>,
}

impl SimulatedVenue {
    pub fn new(fill_model: FillModel) -> Self {
        Self {
            fill_model,
            pending: Mutex::new(Vec::new()),
            fills: Mutex::new(Vec::new()),
        }
    }

    pub async fn place_order(&self, order: PendingOrder) {
        self.pending.lock().await.push(order);
    }

    /// Fill every pending order whose `placed_at` is strictly before
    /// `candle_time`.  Returns the fills produced; removes them from the
    /// pending queue.
    pub async fn apply_candle_close(
        &self,
        close_price: u64,
        candle_time: DateTime<Utc>,
    ) -> Vec<SimulatedFill> {
        let mut pending = self.pending.lock().await;
        let mut all_fills = self.fills.lock().await;

        let mut remaining = Vec::with_capacity(pending.len());
        let mut new_fills = Vec::new();

        for order in pending.drain(..) {
            if candle_time > order.placed_at {
                let fill_price = self.fill_model.apply(close_price, &order.side);
                let fill = SimulatedFill {
                    order_id: order.order_id,
                    side: order.side,
                    quantity: order.quantity,
                    fill_price,
                    strategy_id: order.strategy_id,
                    candle_time,
                };
                all_fills.push(fill.clone());
                new_fills.push(fill);
            } else {
                remaining.push(order);
            }
        }
        *pending = remaining;
        new_fills
    }

    pub async fn all_fills(&self) -> Vec<SimulatedFill> {
        self.fills.lock().await.clone()
    }
}

#[cfg(test)]
mod tests {
    use chrono::TimeZone;

    use super::*;

    fn t(secs: i64) -> DateTime<Utc> {
        Utc.timestamp_opt(secs, 0).unwrap()
    }

    fn pending(side: &str, placed_at: DateTime<Utc>) -> PendingOrder {
        PendingOrder {
            order_id: "ord-1".to_string(),
            side: side.to_string(),
            quantity: 1,
            strategy_id: "strat".to_string(),
            placed_at,
        }
    }

    #[tokio::test(flavor = "current_thread")]
    async fn simulated_venue_empty_pending_returns_empty_fills() {
        let venue = SimulatedVenue::new(FillModel::LastClose);
        let fills = venue.apply_candle_close(100_000, t(1000)).await;
        assert!(fills.is_empty());
    }

    #[tokio::test(flavor = "current_thread")]
    async fn simulated_venue_fills_market_order_at_next_candle_close() {
        let venue = SimulatedVenue::new(FillModel::LastClose);
        venue.place_order(pending("buy", t(1000))).await;

        // Candle AFTER placed_at must produce a fill
        let fills = venue.apply_candle_close(90_000, t(2000)).await;
        assert_eq!(fills.len(), 1);
        assert_eq!(fills[0].fill_price, 90_000);
        assert_eq!(fills[0].side, "buy");
    }

    #[tokio::test(flavor = "current_thread")]
    async fn time_frontier_blocks_lookahead() {
        let venue = SimulatedVenue::new(FillModel::LastClose);
        // Order placed at t=2000
        venue.place_order(pending("buy", t(2000))).await;

        // Candle from BEFORE placed_at must NOT fill
        let fills = venue.apply_candle_close(100_000, t(1000)).await;
        assert!(
            fills.is_empty(),
            "past candle must not fill an order (look-ahead bias)"
        );

        // Candle AT EXACTLY placed_at must NOT fill (strictly-after invariant)
        let fills = venue.apply_candle_close(100_000, t(2000)).await;
        assert!(
            fills.is_empty(),
            "same-timestamp candle must not fill an order"
        );

        // Candle STRICTLY AFTER placed_at must fill
        let fills = venue.apply_candle_close(100_000, t(3000)).await;
        assert_eq!(fills.len(), 1, "future candle must fill the pending order");
        assert_eq!(fills[0].fill_price, 100_000);
    }

    #[tokio::test(flavor = "current_thread")]
    async fn fill_model_last_close_fills_at_exact_price() {
        let model = FillModel::LastClose;
        assert_eq!(model.apply(100_000, "buy"), 100_000);
        assert_eq!(model.apply(100_000, "sell"), 100_000);
    }

    #[tokio::test(flavor = "current_thread")]
    async fn fill_model_slippage_increases_buy_fill_price() {
        let model = FillModel::Slippage { basis_points: 100 }; // 1 %
        let fill = model.apply(100_000, "buy");
        assert!(fill > 100_000, "buy fill must be above close with slippage");
        assert_eq!(fill, 101_000); // 100_000 + 1 % = 101_000
    }

    #[tokio::test(flavor = "current_thread")]
    async fn fill_model_slippage_decreases_sell_fill_price() {
        let model = FillModel::Slippage { basis_points: 100 }; // 1 %
        let fill = model.apply(100_000, "sell");
        assert!(
            fill < 100_000,
            "sell fill must be below close with slippage"
        );
        assert_eq!(fill, 99_000); // 100_000 - 1 % = 99_000
    }

    #[tokio::test(flavor = "current_thread")]
    async fn simulated_venue_all_pending_filled_at_same_close() {
        let venue = SimulatedVenue::new(FillModel::LastClose);
        venue
            .place_order(PendingOrder {
                order_id: "ord-a".to_string(),
                side: "buy".to_string(),
                quantity: 1,
                strategy_id: "s".to_string(),
                placed_at: t(1000),
            })
            .await;
        venue
            .place_order(PendingOrder {
                order_id: "ord-b".to_string(),
                side: "sell".to_string(),
                quantity: 2,
                strategy_id: "s".to_string(),
                placed_at: t(1000),
            })
            .await;

        let fills = venue.apply_candle_close(90_000, t(2000)).await;
        assert_eq!(fills.len(), 2, "both pending orders must be filled");
    }

    #[tokio::test(flavor = "current_thread")]
    async fn simulated_venue_filled_orders_not_applied_twice() {
        let venue = SimulatedVenue::new(FillModel::LastClose);
        venue.place_order(pending("buy", t(1000))).await;

        let fills_first = venue.apply_candle_close(100_000, t(2000)).await;
        assert_eq!(fills_first.len(), 1);

        // Second apply must not produce duplicate fills
        let fills_second = venue.apply_candle_close(100_000, t(3000)).await;
        assert!(
            fills_second.is_empty(),
            "already-filled order must not be applied twice"
        );
    }
}
