use std::fmt;

use async_trait::async_trait;
use rust_decimal::Decimal;
use thiserror::Error;

use crate::exchange::entity::ExchangeId;

#[derive(Debug, Clone, PartialEq)]
pub enum OrderSide {
    Buy,
    Sell,
}

impl fmt::Display for OrderSide {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            OrderSide::Buy => write!(f, "buy"),
            OrderSide::Sell => write!(f, "sell"),
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum OrderType {
    Market,
    Limit,
}

impl fmt::Display for OrderType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            OrderType::Market => write!(f, "market"),
            OrderType::Limit => write!(f, "limit"),
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum OrderStatus {
    Open,
    Filled,
    PartiallyFilled,
    Cancelled,
    Failed,
}

impl fmt::Display for OrderStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            OrderStatus::Open => write!(f, "open"),
            OrderStatus::Filled => write!(f, "filled"),
            OrderStatus::PartiallyFilled => write!(f, "partially_filled"),
            OrderStatus::Cancelled => write!(f, "cancelled"),
            OrderStatus::Failed => write!(f, "failed"),
        }
    }
}

/// Exchange-assigned identifier for a placed order.
#[derive(Debug, Clone, PartialEq)]
pub struct OrderId(pub String);

/// Result of a status query, including the optional fill price for filled orders.
#[derive(Debug, Clone, PartialEq)]
pub struct OrderStatusResult {
    pub status: OrderStatus,
    /// Actual fill price returned by the exchange. `None` for non-filled statuses
    /// or when the exchange does not include price in the status response.
    pub fill_price: Option<Decimal>,
}

impl OrderStatusResult {
    pub fn new(status: OrderStatus) -> Self {
        Self {
            status,
            fill_price: None,
        }
    }

    pub fn filled(fill_price: Decimal) -> Self {
        Self {
            status: OrderStatus::Filled,
            fill_price: Some(fill_price),
        }
    }
}

/// Outcome of reconciling an order by its client-assigned id after a transient
/// placement failure: the exchange-assigned id plus the order's current status.
#[derive(Debug, Clone, PartialEq)]
pub struct ReconciledOrder {
    pub order_id: OrderId,
    pub result: OrderStatusResult,
}

impl fmt::Display for OrderId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Everything the adapter needs to construct and send an order to the exchange.
#[derive(Debug, Clone)]
pub struct OrderRequest {
    /// Canonical exchange name (e.g. "tabdeal").
    pub exchange: String,
    /// Trading pair in "BASE/QUOTE" form (e.g. "USDT/IRT").
    pub pair: String,
    pub side: OrderSide,
    pub order_type: OrderType,
    /// Quantity in base currency. Must use Decimal — never f64.
    pub quantity: Decimal,
    /// Limit price in quote currency. `None` for market orders.
    pub price: Option<Decimal>,
    /// UUID generated by the caller before any DB or network operation.
    /// Sent to the exchange as `newClientOrderId` (or equivalent) so the
    /// exchange can deduplicate on its side.
    pub client_order_id: String,
    /// Set when the order originates from a strategy signal.
    pub strategy_id: Option<String>,
}

/// Errors produced by an `OrderAdapter`.
///
/// Every variant must be classified as transient or permanent via
/// `is_transient()`. The Order Manager uses this to decide whether to retry.
#[derive(Debug, Error)]
pub enum OrderAdapterError {
    /// Transient — network did not respond within the hard deadline.
    #[error("network timeout: {0}")]
    NetworkTimeout(String),

    /// Transient — exchange returned 5xx.
    #[error("server error: status={status}, body={body}")]
    ServerError { status: u16, body: String },

    /// Permanent — exchange rejected the order (4xx with a business-logic reason).
    #[error("order rejected: {0}")]
    Rejected(String),

    /// Permanent — pair is not traded on this exchange.
    #[error("unknown symbol: {0}")]
    UnknownSymbol(String),

    /// Permanent — account does not have sufficient funds.
    #[error("insufficient funds")]
    InsufficientFunds,

    /// Permanent — API key is missing, expired, or invalid.
    #[error("authentication failed")]
    AuthFailed,

    /// Permanent — could not serialize the request or deserialize the response.
    #[error("serialization error: {0}")]
    Serialization(String),
}

/// Detects a Binance-compatible "order does not exist" response body (HTTP 4xx) —
/// the signal that an order being reconciled never reached the exchange. Shared by
/// every Binance-shaped order adapter (Tabdeal, Hitobit, Exir).
pub(crate) fn is_order_not_found_body(body: &str) -> bool {
    let Ok(v) = serde_json::from_str::<serde_json::Value>(body) else {
        return false;
    };
    if v["code"].as_i64() == Some(-2013) {
        return true;
    }
    let msg = v["msg"]
        .as_str()
        .or_else(|| v["message"].as_str())
        .or_else(|| v["error"].as_str())
        .unwrap_or("")
        .to_lowercase();
    msg.contains("does not exist") || msg.contains("not found") || msg.contains("unknown order")
}

impl OrderAdapterError {
    /// Returns `true` for errors that are safe to retry.
    ///
    /// Permanent errors (4xx, auth failures, unknown symbols) must never be
    /// retried — they will fail again with the same result.
    pub fn is_transient(&self) -> bool {
        matches!(self, Self::NetworkTimeout(_) | Self::ServerError { .. })
    }
}

#[async_trait]
pub trait OrderAdapter: Send + Sync {
    /// Returns the canonical exchange identifier this adapter serves.
    fn exchange_id(&self) -> ExchangeId;

    /// Places a new order. Returns the exchange-assigned `OrderId`.
    ///
    /// The caller must persist `req.client_order_id` atomically with the order
    /// record in the database **before** calling this method. On a transient
    /// failure (`NetworkTimeout` / `ServerError`), reconcile with
    /// `get_order_status_by_client_id` before marking the order failed — the
    /// request may have reached the exchange even though the response was lost.
    async fn place_order(&self, req: &OrderRequest) -> Result<OrderId, OrderAdapterError>;

    /// Requests cancellation of an open order.
    async fn cancel_order(&self, order_id: &OrderId) -> Result<(), OrderAdapterError>;

    /// Fetches the current status of an order. Used to reconcile after a
    /// `NetworkTimeout` on placement and by the fill poller.
    /// Returns `OrderStatusResult` which includes the fill price when available.
    async fn get_order_status(
        &self,
        order_id: &OrderId,
    ) -> Result<OrderStatusResult, OrderAdapterError>;

    /// Reconciles an order's true state by its **client-assigned** id, used after
    /// a transient error or timeout on placement where the exchange-assigned
    /// `OrderId` is unknown. The request may have reached the exchange even though
    /// the caller observed an error — marking such an order `failed` would orphan
    /// a live position.
    ///
    /// - `Ok(Some(reconciled))` — the exchange has the order; adopt its id + status.
    /// - `Ok(None)` — the exchange has no record; the order never landed (safe to fail).
    /// - `Err(_)` — reconciliation itself failed; the true state is unknown and the
    ///   caller must NOT mark the order `failed`.
    async fn get_order_status_by_client_id(
        &self,
        client_order_id: &str,
    ) -> Result<Option<ReconciledOrder>, OrderAdapterError>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn order_side_buy_displays_as_buy() {
        assert_eq!(OrderSide::Buy.to_string(), "buy");
    }

    #[test]
    fn order_side_sell_displays_as_sell() {
        assert_eq!(OrderSide::Sell.to_string(), "sell");
    }

    #[test]
    fn order_type_limit_displays_as_limit() {
        assert_eq!(OrderType::Limit.to_string(), "limit");
    }

    #[test]
    fn order_type_market_displays_as_market() {
        assert_eq!(OrderType::Market.to_string(), "market");
    }

    #[test]
    fn order_status_open_displays_as_open() {
        assert_eq!(OrderStatus::Open.to_string(), "open");
    }

    #[test]
    fn order_status_filled_displays_as_filled() {
        assert_eq!(OrderStatus::Filled.to_string(), "filled");
    }

    #[test]
    fn order_id_display_returns_inner_string() {
        let id = OrderId("exchange-12345".to_string());
        assert_eq!(id.to_string(), "exchange-12345");
    }

    #[test]
    fn order_adapter_error_network_timeout_is_transient() {
        let err = OrderAdapterError::NetworkTimeout("timed out".to_string());
        assert!(err.is_transient(), "NetworkTimeout must be transient");
    }

    #[test]
    fn order_adapter_error_server_error_is_transient() {
        let err = OrderAdapterError::ServerError {
            status: 503,
            body: "service unavailable".to_string(),
        };
        assert!(err.is_transient(), "5xx ServerError must be transient");
    }

    #[test]
    fn order_adapter_error_rejected_is_not_transient() {
        let err = OrderAdapterError::Rejected("minimum quantity not met".to_string());
        assert!(!err.is_transient(), "Rejected must be permanent");
    }

    #[test]
    fn order_adapter_error_unknown_symbol_is_not_transient() {
        let err = OrderAdapterError::UnknownSymbol("XYZIRT".to_string());
        assert!(!err.is_transient());
    }

    #[test]
    fn order_adapter_error_insufficient_funds_is_not_transient() {
        assert!(!OrderAdapterError::InsufficientFunds.is_transient());
    }

    #[test]
    fn order_adapter_error_auth_failed_is_not_transient() {
        assert!(!OrderAdapterError::AuthFailed.is_transient());
    }

    #[test]
    fn order_request_stores_client_order_id() {
        let req = OrderRequest {
            exchange: "tabdeal".to_string(),
            pair: "USDT/IRT".to_string(),
            side: OrderSide::Buy,
            order_type: OrderType::Limit,
            quantity: Decimal::new(100, 0),
            price: Some(Decimal::new(58_000, 0)),
            client_order_id: "test-uuid-1234".to_string(),
            strategy_id: None,
        };
        assert_eq!(req.client_order_id, "test-uuid-1234");
    }

    #[test]
    fn order_status_result_new_has_no_fill_price() {
        let r = OrderStatusResult::new(OrderStatus::Open);
        assert_eq!(r.status, OrderStatus::Open);
        assert!(r.fill_price.is_none());
    }

    #[test]
    fn order_status_result_filled_carries_fill_price() {
        let price = Decimal::new(58_000, 0);
        let r = OrderStatusResult::filled(price);
        assert_eq!(r.status, OrderStatus::Filled);
        assert_eq!(r.fill_price, Some(price));
    }

    #[test]
    fn reconciled_order_carries_exchange_id_and_status() {
        let r = ReconciledOrder {
            order_id: OrderId("exch-77".to_string()),
            result: OrderStatusResult::filled(Decimal::new(58_000, 0)),
        };
        assert_eq!(r.order_id.0, "exch-77");
        assert_eq!(r.result.status, OrderStatus::Filled);
        assert_eq!(r.result.fill_price, Some(Decimal::new(58_000, 0)));
    }
}
