CREATE TABLE IF NOT EXISTS assets (
    id           SERIAL PRIMARY KEY,
    symbol       TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    decimals     SMALLINT NOT NULL,
    icon_url     TEXT,
    active       BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO assets (symbol, display_name, decimals) VALUES
    ('AAVE', 'Aave', 8),
    ('ADA', 'Cardano', 6),
    ('ALGO', 'Algorand', 6),
    ('APT', 'Aptos', 8),
    ('ARB', 'Arbitrum', 8),
    ('ATOM', 'Cosmos', 6),
    ('AVAX', 'Avalanche', 8),
    ('AXS', 'Axie Infinity', 8),
    ('BCH', 'Bitcoin Cash', 8),
    ('BNB', 'BNB', 8),
    ('BTC', 'Bitcoin', 8),
    ('BTT', 'BitTorrent', 8),
    ('CAKE', 'PancakeSwap', 8),
    ('CHZ', 'Chiliz', 8),
    ('COMP', 'Compound', 8),
    ('CRV', 'Curve DAO Token', 8),
    ('DAI', 'Dai', 6),
    ('DASH', 'Dash', 8),
    ('DOGE', 'Dogecoin', 8),
    ('DOT', 'Polkadot', 8),
    ('DYDX', 'dYdX', 8),
    ('EGLD', 'MultiversX', 8),
    ('ENJ', 'Enjin Coin', 8),
    ('EOS', 'EOS', 6),
    ('ETC', 'Ethereum Classic', 8),
    ('ETH', 'Ethereum', 8),
    ('FIL', 'Filecoin', 8),
    ('FLOW', 'Flow', 8),
    ('FTM', 'Fantom', 8),
    ('GALA', 'Gala', 8),
    ('GMT', 'STEPN', 8),
    ('GRT', 'The Graph', 8),
    ('HBAR', 'Hedera', 8),
    ('ICP', 'Internet Computer', 8),
    ('IMX', 'Immutable', 8),
    ('INJ', 'Injective', 8),
    ('IOTA', 'IOTA', 6),
    ('IRT', 'Iranian Toman', 0),
    ('KAVA', 'Kava', 8),
    ('KLAY', 'Klaytn', 8),
    ('KSM', 'Kusama', 8),
    ('LDO', 'Lido DAO', 8),
    ('LINK', 'Chainlink', 8),
    ('LRC', 'Loopring', 8),
    ('LTC', 'Litecoin', 8),
    ('LUNA', 'Terra', 8),
    ('MANA', 'Decentraland', 8),
    ('MASK', 'Mask Network', 8),
    ('MATIC', 'Polygon', 8),
    ('MINA', 'Mina', 8),
    ('MKR', 'Maker', 8),
    ('NEAR', 'NEAR Protocol', 8),
    ('NEO', 'Neo', 8),
    ('OCEAN', 'Ocean Protocol', 8),
    ('OMG', 'OMG Network', 8),
    ('ONE', 'Harmony', 8),
    ('OP', 'Optimism', 8),
    ('PEPE', 'Pepe', 8),
    ('QNT', 'Quant', 8),
    ('QTUM', 'Qtum', 8),
    ('RNDR', 'Render', 8),
    ('ROSE', 'Oasis Network', 8),
    ('RUNE', 'THORChain', 8),
    ('RVN', 'Ravencoin', 8),
    ('SAND', 'The Sandbox', 8),
    ('SHIB', 'Shiba Inu', 8),
    ('SNX', 'Synthetix', 8),
    ('SOL', 'Solana', 8),
    ('STX', 'Stacks', 8),
    ('SUI', 'Sui', 8),
    ('SUSHI', 'SushiSwap', 8),
    ('THETA', 'Theta Network', 8),
    ('TON', 'Toncoin', 8),
    ('TRX', 'TRON', 6),
    ('TUSD', 'TrueUSD', 6),
    ('UNI', 'Uniswap', 8),
    ('USDC', 'USD Coin', 6),
    ('USDT', 'Tether', 6),
    ('VET', 'VeChain', 8),
    ('WAVES', 'Waves', 8),
    ('WBTC', 'Wrapped Bitcoin', 8),
    ('XEC', 'eCash', 2),
    ('XLM', 'Stellar', 7),
    ('XMR', 'Monero', 12),
    ('XRP', 'XRP', 6),
    ('XTZ', 'Tezos', 6),
    ('YFI', 'yearn.finance', 8),
    ('ZEC', 'Zcash', 8),
    ('ZEN', 'Horizen', 8),
    ('ZIL', 'Zilliqa', 8),
    ('ZRX', '0x', 8),
    ('1INCH', '1inch', 8),
    ('AGIX', 'SingularityNET', 8),
    ('ANKR', 'Ankr', 8),
    ('AR', 'Arweave', 8),
    ('BAT', 'Basic Attention Token', 8),
    ('BAL', 'Balancer', 8),
    ('BSV', 'Bitcoin SV', 8),
    ('CELO', 'Celo', 8),
    ('CFX', 'Conflux', 8),
    ('CKB', 'Nervos Network', 8),
    ('CVC', 'Civic', 8),
    ('CVX', 'Convex Finance', 8),
    ('DGB', 'DigiByte', 8),
    ('ENS', 'Ethereum Name Service', 8),
    ('FXS', 'Frax Share', 8),
    ('GLMR', 'Moonbeam', 8),
    ('GNO', 'Gnosis', 8),
    ('JASMY', 'JasmyCoin', 8),
    ('JST', 'JUST', 8)
ON CONFLICT (symbol) DO NOTHING;
