name: Release Pipeline

on:
  push:
    tags:
      - "v*.*.*"       # example v1.0.0, v2.3.4
      - "v*.*.*-*.*"   # example v1.0.0-alpha.1, v1.0.0-beta.2, v1.0.0-rc.1
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (example v1.0.0-alpha.1, v1.0.0-rc.1, v1.3.4)"
        required: true
        default: "v0.0.1-alpha"

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      #- name: Check formatting
      #  run: cargo fmt --all -- --check

      #- name: Run clippy
      #  run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all-features

  build:
    needs: test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: stream-coin
            asset_name: stream-coin-linux-x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: stream-coin
            asset_name: stream-coin-linux-x86_64-musl
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: stream-coin.exe
            asset_name: stream-coin-windows-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: stream-coin
            asset_name: stream-coin-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: stream-coin
            asset_name: stream-coin-macos-arm64
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        shell: bash
        run: echo "version=${{ github.event.inputs.version || github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install musl tools (Linux musl only)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-

      - name: Build release binary
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Strip binary (Unix only)
        if: matrix.os != 'windows-latest'
        run: strip target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

      - name: Create archive (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          tar -czf ${{ matrix.asset_name }}-${{ steps.get_version.outputs.version }}.tar.gz ${{ matrix.artifact_name }}
          sha256sum ${{ matrix.asset_name }}-${{ steps.get_version.outputs.version }}.tar.gz > ${{ matrix.asset_name }}-${{ steps.get_version.outputs.version }}.tar.gz.sha256

      - name: Create archive (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          cd target/${{ matrix.target }}/release
          Compress-Archive -Path ${{ matrix.artifact_name }} -DestinationPath ${{ matrix.asset_name }}-${{ steps.get_version.outputs.version }}.zip
          (Get-FileHash ${{ matrix.asset_name }}-${{ steps.get_version.outputs.version }}.zip -Algorithm SHA256).Hash | Out-File -FilePath ${{ matrix.asset_name }}-${{ steps.get_version.outputs.version }}.zip.sha256 -NoNewline

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}-${{ steps.get_version.outputs.version }}
          path: |
            target/${{ matrix.target }}/release/${{ matrix.asset_name }}-${{ steps.get_version.outputs.version }}.*

  build-deb:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo "version=${{ github.event.inputs.version || github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-deb-${{ hashFiles('**/Cargo.lock') }}

      - name: Build .deb package
        run: cargo deb

      - name: Rename .deb file
        run: |
          DEB_FILE=$(find target/debian -name "*.deb")
          mv $DEB_FILE target/debian/stream-coin-${{ steps.get_version.outputs.version }}-amd64.deb
          sha256sum target/debian/stream-coin-${{ steps.get_version.outputs.version }}-amd64.deb > target/debian/stream-coin-${{ steps.get_version.outputs.version }}-amd64.deb.sha256

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: stream-coin-deb-${{ steps.get_version.outputs.version }}
          path: target/debian/*.deb*

  build-rpm:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo "version=${{ github.event.inputs.version || github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-generate-rpm
        run: cargo install cargo-generate-rpm

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-rpm-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release

      - name: Strip binary
        run: strip target/release/stream-coin

      - name: Build .rpm package
        run: cargo generate-rpm

      - name: Rename .rpm file
        run: |
          RPM_FILE=$(find target/generate-rpm -name "*.rpm")
          mv $RPM_FILE target/generate-rpm/stream-coin-${{ steps.get_version.outputs.version }}-1.x86_64.rpm
          sha256sum target/generate-rpm/stream-coin-${{ steps.get_version.outputs.version }}-1.x86_64.rpm > target/generate-rpm/stream-coin-${{ steps.get_version.outputs.version }}-1.x86_64.rpm.sha256

      - name: Upload .rpm artifact
        uses: actions/upload-artifact@v4
        with:
          name: stream-coin-rpm-${{ steps.get_version.outputs.version }}
          path: target/generate-rpm/*.rpm*

  build-msi:
    needs: test
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        shell: bash
        run: echo "version=${{ github.event.inputs.version || github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-wix
        run: cargo install cargo-wix

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-wix-${{ hashFiles('**/Cargo.lock') }}

      - name: Build .msi installer
        run: cargo wix --nocapture

      - name: Rename .msi file
        shell: pwsh
        run: |
          $MSI_FILE = Get-ChildItem -Path target\wix -Filter *.msi | Select-Object -First 1
          Move-Item $MSI_FILE.FullName "target\wix\stream-coin-${{ steps.get_version.outputs.version }}-x64.msi"
          (Get-FileHash "target\wix\stream-coin-${{ steps.get_version.outputs.version }}-x64.msi" -Algorithm SHA256).Hash | Out-File -FilePath "target\wix\stream-coin-${{ steps.get_version.outputs.version }}-x64.msi.sha256" -NoNewline

      - name: Upload .msi artifact
        uses: actions/upload-artifact@v4
        with:
          name: stream-coin-msi-${{ steps.get_version.outputs.version }}
          path: target/wix/*.msi*

  build-appimage:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo "version=${{ github.event.inputs.version || github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-appimage-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release

      - name: Download AppImage tools
        run: |
          wget -c https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage

      - name: Create AppDir structure
        run: |
          mkdir -p AppDir/usr/bin
          cp target/release/stream-coin AppDir/usr/bin/
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps

      - name: Create .desktop file
        run: |
          cat > AppDir/usr/share/applications/stream-coin.desktop << EOF
          [Desktop Entry]
          Type=Application
          Name=Stream Coin
          Exec=stream-coin
          Icon=stream-coin
          Categories=Utility;
          EOF

      - name: Create AppImage
        run: |
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage
          mv Stream_Coin*.AppImage stream-coin-${{ steps.get_version.outputs.version }}-x86_64.AppImage
          sha256sum stream-coin-${{ steps.get_version.outputs.version }}-x86_64.AppImage > stream-coin-${{ steps.get_version.outputs.version }}-x86_64.AppImage.sha256

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: stream-coin-appimage-${{ steps.get_version.outputs.version }}
          path: |
            stream-coin-${{ steps.get_version.outputs.version }}-x86_64.AppImage*

  release:
    needs: [build, build-deb, build-rpm, build-msi, build-appimage]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo "version=${{ github.event.inputs.version || github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          tag_name: ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: ${{ contains(steps.get_version.outputs.version, '-alpha') || contains(steps.get_version.outputs.version, '-beta') || contains(steps.get_version.outputs.version, '-rc') }}
          generate_release_notes: true

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: release
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/stream-coin
          tags: |
            type=semver,pattern={{version}},value=${{ needs.release.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.release.outputs.version }}
            type=semver,pattern={{major}},value=${{ needs.release.outputs.version }}
            type=raw,value=latest,enable=${{ !contains(needs.release.outputs.version, '-') }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ needs.release.outputs.version }}
